import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link';

import HeroPost from '@/components/hero-post';
import styles from '@/styles/Home.module.scss'
import type { PostType } from "types/post";
import { getAllPosts } from "libs/api/api";

type Props = {
  allPosts: Array<PostType>;
};

export default function Home({ allPosts }: Props) {
  const heroPost = allPosts[0]
  const morePosts = allPosts.slice(1)
  return (
    <>
      <Head>
        <title>Polskaa&apos;s BLOG</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta property="og:url" content=" ページのURL" />
        <meta property="og:type" content=" ページの種類" />
        <meta property="og:title" content=" ページのタイトル" />
        <meta property="og:description" content=" ページの説明文" />
        <meta property="og:site_name" content="サイト名" />
        <meta property="og:image" content=" サムネイル画像のURL" />
      </Head>
      <main className={styles.container}>
        <div className={styles.contents}>
          <HeroPost
            title={heroPost.title}
            date={heroPost.date}
            slug={heroPost.slug}
            excerpt={heroPost.excerpt}
          />
        </div>
      </main>
    </>
  )
}

export const getStaticProps = async () => {
  const allPosts = getAllPosts([
    'title',
    'date',
    'slug',
    'author',
    'coverImage',
    'excerpt',
  ])

  return {
    props: { allPosts },
  }
}